--ACCEPT로 부서번호 입력받아 부서 총합 출력 

ACCEPT V_DEPTNO PROMPT '부서번호를 입력하세요.>'

DECLARE
	VDEPTNO EMP.DEPTNO%TYPE := &V_DEPTNO;
	VSUMSAL EMP.SAL%TYPE;
BEGIN
	SELECT SUM(SAL)
	INTO VSUMSAL
	FROM EMP
	WHERE DEPTNO = VDEPTNO;

	IF (VSUMSAL IS NULL) THEN
		DBMS_OUTPUT.PUT_LINE('해당 부서는 없습니다');
	ELSE
		DBMS_OUTPUT.PUT_LINE(VDEPTNO || '번 부서 급여 총합은 ' || VSUMSAL || '입니다');
	END IF;
END;
/