--IF문으로 특정 사번의 부서번호의 부서명 출력
DECLARE
	VEMPNO EMP.EMPNO%TYPE;
	VENAME EMP.ENAME%TYPE;
	VDEPTNO DEPT.DEPTNO%TYPE;
	VDNAME DEPT.DNAME%TYPE;

BEGIN
	SELECT EMPNO, ENAME, DEPTNO
	INTO VEMPNO, VENAME, VDEPTNO
	FROM EMP
	WHERE EMPNO = 7788;

	IF (VDEPTNO=10) THEN
		VDNAME := 'ACCOUNTING';
	END IF;
	
	IF (VDEPTNO=20) THEN
		VDNAME := 'RESEARCH';
	END IF;

	IF (VDEPTNO=30) THEN
		VDNAME := 'SALES';
	END IF;

	IF (VDEPTNO=40) THEN
		VDNAME := 'OPERATION';
	END IF;

	DBMS_OUTPUT.PUT_LINE('사번   이름   부서명');
	DBMS_OUTPUT.PUT_LINE(VEMPNO || '   ' || VENAME || '   ' || VDNAME);
END;
/