--사원번호로 부서명 알아내기

DECLARE 
	VEMPNO EMP.EMPNO%TYPE;
	VENAME EMP.ENAME%TYPE;
	VDNAME	DEPT.DNAME%TYPE;

BEGIN
	SELECT EMP.EMPNO, EMP.ENAME, DEPT.DNAME
	INTO VEMPNO, VENAME, VDNAME
	FROM EMP, DEPT
	WHERE EMP.DEPTNO = DEPT.DEPTNO
	AND EMPNO=7788;

	DBMS_OUTPUT.PUT_LINE('사번 / 이름 / 부서명');
	DBMS_OUTPUT.PUT_LINE('----------------------');
	DBMS_OUTPUT.PUT_LINE(VEMPNO || ' / ' || VENAME || ' / ' || VDNAME);

END;
/