-- 사원명으로 검색해 해당 사원 직급 얻어오는 프로시저

CREATE OR REPLACE PROCEDURE SEL_EMPNAME(
	VENAME IN EMP01.ENAME%TYPE,
	VJOB OUT EMP01.JOB%TYPE)
IS
BEGIN
	SELECT JOB
	INTO VJOB
	FROM EMP01
	WHERE ENAME = VENAME;
END;
/