--사원명으로 검색해 해당 사원 직급 얻어오는 저장함수

CREATE OR REPLACE FUNCTION SEL_EMPNAME02(
	VENAME EMP01.ENAME%TYPE)
RETURN VARCHAR2(15)
IS
	VJOB VARCHAR2(15);	
BEGIN
	SELECT JOB
	INTO VJOB
	FROM EMP01
	WHERE ENAME = VENAME;

	RETURN VJOB;
END;